-- Add Economic System columns to users table
ALTER TABLE users 
ADD COLUMN IF NOT EXISTS subscription_tier text DEFAULT 'free',
ADD COLUMN IF NOT EXISTS commission_rate integer DEFAULT 20;

-- Add Sales Logic to products table
ALTER TABLE products
ADD COLUMN IF NOT EXISTS sale_price integer,
ADD COLUMN IF NOT EXISTS sale_ends_at timestamp with time zone;

-- Create Payouts table
CREATE TABLE IF NOT EXISTS payouts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES users(id) ON DELETE CASCADE NOT NULL,
  amount integer NOT NULL, -- in cents
  status text DEFAULT 'pending', -- pending, processed, rejected
  method text DEFAULT 'stripe',
  requested_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  processed_at timestamp with time zone
);

-- Enable RLS on Payouts
ALTER TABLE payouts ENABLE ROW LEVEL SECURITY;

-- Payouts Policies
CREATE POLICY "Users can view their own payouts"
  ON payouts FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can create payout requests"
  ON payouts FOR INSERT
  WITH CHECK (auth.uid() = user_id);

-- Only admins/service role can update payouts (process them)
-- No policy for UPDATE for normal users, effectively limiting them.
